### ISSUE TITLE
WARN: No variants installed, did you forget to use --expert?

### ISSUE THREAD

**Issue by matheusho** [uber-archive/potter#10]
Hi, guys.

I see this project on a presentation of @Raynos about Building High Quality Services.

I've been testing and found some problems:

**Steps**
1 - `npm install potter -g`
2 - `npm potter create steak-house`

**Console**
`WARN: No variants installed, did you forget to use --expert?`

Node version: 0.10.32.

Some suggestion for solve this problem?

Thanks.

**Comment by Raynos** [comment]
I'm afraid this tool never made it. Project got replaced.

However all the libraries I talked about in my talk are still open source and used in production.
